### ISSUE TITLE
Bacsic cannot run start

### ISSUE THREAD

**Issue by huylinh620** [CKGrafico/Gulp-Boilerplates#144]
```
PS D:\Work\template\Frontend-Boilerplates-basic> npm run start

> basic-spa@3.0.1 start D:\Work\template\Frontend-Boilerplates-basic
> webpack serve --hot --open --mode development

[webpack-cli] Failed to load 'D:\Work\template\Frontend-Boilerplates-basic\webpack.config.js' config
[webpack-cli] Error: Cannot find module './src/styles/functions/post-functions.js'
Require stack:
- D:\Work\template\Frontend-Boilerplates-basic\tasks\rules\styles.js
- D:\Work\template\Frontend-Boilerplates-basic\node_modules\require.all\index.js
- D:\Work\template\Frontend-Boilerplates-basic\webpack.config.js
- D:\Work\template\Frontend-Boilerplates-basic\node_modules\webpack-cli\lib\webpack-cli.js
- D:\Work\template\Frontend-Boilerplates-basic\node_modules\webpack-cli\lib\bootstrap.js
- D:\Work\template\Frontend-Boilerplates-basic\node_modules\webpack-cli\bin\cli.js
- D:\Work\template\Frontend-Boilerplates-basic\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (D:\Work\template\Frontend-Boilerplates-basic\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\Work\template\Frontend-Boilerplates-basic\tasks\rules\styles.js:3:28)
    at Module._compile (D:\Work\template\Frontend-Boilerplates-basic\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Work\\template\\Frontend-Boilerplates-basic\\tasks\\rules\\styles.js',
    'D:\\Work\\template\\Frontend-Boilerplates-basic\\node_modules\\require.all\\index.js',
    'D:\\Work\\template\\Frontend-Boilerplates-basic\\webpack.config.js',
    'D:\\Work\\template\\Frontend-Boilerplates-basic\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'D:\\Work\\template\\Frontend-Boilerplates-basic\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'D:\\Work\\template\\Frontend-Boilerplates-basic\\node_modules\\webpack-cli\\bin\\cli.js',
    'D:\\Work\\template\\Frontend-Boilerplates-basic\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! basic-spa@3.0.1 start: `webpack serve --hot --open --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the basic-spa@3.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I can't fix it. You can help me fix it!

**Comment by CKGrafico** [comment]
The packagejson is a little bit outdated.. can you try now please? remove your node modules first
